### ISSUE TITLE
Just using the biggest node?

### ISSUE THREAD

**Issue by kmader** [booz-allen-hamilton/DSB3Tutorial#2]
The training for UNET just using the biggest node (https://github.com/booz-allen-hamilton/DSB3Tutorial/blob/master/tutorial_code/LUNA_mask_extraction.py#L88) seems somewhat arbitrary. It would make more sense to use all of them so the training set has as many training points as possible (~ a factor of 3 increase)

**Comment by jonrmulholland** [comment]
Thanks for the fix
