### ISSUE TITLE
issue with nodules.npy in classify_nodes!

### ISSUE THREAD

**Issue by prateeknepaliya09** [booz-allen-hamilton/DSB3Tutorial#23]
Where does it come from? It's not even generated!

**Comment by itcthienkhiem** [comment]
this is "masksTestPredicted.npy"

**Comment by aszhanghuali** [comment]
@itcthienkhiem 
Hi！I'm so sorry to bother you!I just wanna to confirm whether "nodules.npy" is 
"masksTestPredicted.npy"?
Looking forward your reply！thank you so much!

**Comment by aszhanghuali** [comment]
@prateeknepaliya09 
Hi！I'm so sorry to bother you!I just wanna to confirm whether "nodules.npy" is
"masksTestPredicted.npy"?
Looking forward your reply！thank you so much!

**Comment by prateeknepaliya09** [comment]
@aszhanghuali Yes

**Comment by aszhanghuali** [comment]
@prateeknepaliya09 
Thank you for your reply! I try the fact that "nodules.npy" is
"masksTestPredicted.npy",but in "classify_nodes.py"  there's an error:FileNotFoundError: [Errno 2] No such file or directory: 'E:/one/home/jonathan/tutorial/dataX.npy'
Looking forward your reply！Thank you again!

**Comment by aszhanghuali** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you for your reply! I try the fact that "nodules.npy" is"masksTestPredicted.npy",but in "classify_nodes.py" there's an error:FileNotFoundError: [Errno 2] No such file or directory: 'E:/one/home/jonathan/tutorial/dataX.npy'Looking forward your reply！Thank you again!
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1319466165
                            
                    
                        
                            
                                    1319466165@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/2/2019 02:40，Prateek Nepaliya<notifications@github.com> wrote： 


Closed #23.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by aszhanghuali** [comment]
@prateeknepaliya09 
Thank you for your reply! Did you run the classify_nodules.py successfully?I wanna you share with me !
Looking forward to your reply!
